#+TITLE:DSC 482.01 Fall 2023 Syllabus DRAFT
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: Artificial Intelligence
#+options: toc:nil
* General Course Information

  - Meeting Times: Monday/Wednesday/Friday, 09:00-09:50 hrs
  - Meeting place: Lyon Building computer lab room 104
  - Professor: Marcus Birkenkrahe
  - Office: Derby Science Center room 210
  - Office hours: Mon/Wed 2-3pm, Tue 4-4.45pm, Thu 9.30-10:45am 
  - Phone: (870) 307-7254
  - Textbooks we'll be using:
    1) [[https://aima.cs.berkeley.edu/][AIMA - /Artificial Intelligence - A Modern Approach]] (4th
       edition)/, by Stuart Russell and Peter Norvig, Pearson 2021.
    2) [[https://www.manning.com/books/learn-ai-assisted-python-programming][Learn AI-Assisted Python Programming]] - With GitHub Copilot and
       ChatGPT, by Leo Porter and Daniel Zingaro, Manning 2023.

* Objectives

   Artificial intelligence has been a goal of computer science (CS)
   since the early days of the field in the 1950s. Unlike other areas
   of CS, it has undergone major trend swings. Currently, AI enjoys
   another (its third) spring. In truth, though, AI is not just one
   field, but several interconnected fields. In this seminar, we will
   work together to identify and understand the AI subfields that are
   industrially relevant, and separate them from the more arcane areas
   that may, or may not be relevant in the near future. This special
   topic seminar is for everyone who is interested in AI. We will
   discuss algorithmic, social, philosophical, commercial and
   technical aspects of AI.

* Student Learning Outcomes

   Students who complete DSC 482.01 "Artificial Intelligence", will be
   able to:

   - understand the history and importance of AI for society
   - know how to solve problems in complex environments
   - know how AI can be used for sales and marketing
   - understand agent-based technologies for different applications
   - understand the conceptual basics of machine learning techniques
   - design an own application using AI principles and techniques

* Course requirements

   No prior knowledge required. Some knowledge of, and experience with
   algorithms is useful but not critical. Curiosity is essential. You
   will gain data literacy skills by taking this course. The course
   will prepare you for further studies in machine learning and deep
   learning, but also in conceptual applications of AI, like machine
   ethics.

* Grading system

   | WHEN      | DESCRIPTION          | IMPACT |
   |-----------+----------------------+--------|
   | TBD       | Final exam           |    25% |
   | Last week | Final presentation   |    25% |
   | Weekly    | DataCamp assignments |    25% |
   | Weekly    | Tests                |    25% |

   To pass: 50%

* [[https://docs.google.com/document/d/1ZaoAIX7rdBOsRntBxPk7TK77Vld9NXECVLvT9_Jovwc/edit?usp=sharing][Standard Policies (Spring 2023)]]
* [[https://tinyurl.com/LyonPolicy][Assignments and Honor Code and Attendance Policy]]
* Dates and class schedule (TBC)
