#+title: Introduction to Data Science (DSC 105) Draft Syllabus
#+author: Marcus Birkenkrahe
#+startup: overview hideblocks indent
#+options: toc:1 num:1 ^:nil
#+subtitle: DSC105 Introduction to Data Science - Syllabus (Draft)
* General Course Information

- Course title: Introduction to data science
- Course number and section: DSC 105.01
- Meeting Times: Mon-Wed-Fri from 13:00-13:50 am
- Meeting place: Lyon Building Computer Lab room 104
- Professor: Marcus Birkenkrahe
- Professor's Office: Derby Science Building 210
- Phone: (870) 307-7254 (office) / (501) 422-4725 (private)
- Office hours: Monday through Friday after class
- Textbook: The Book of R (Part I, ch. 1-8) by T Davies
  ([[https://nostarch.com/bookofr][NoStarch, 2016]]) - reserved copy available in the library

* Objectives

Data science is concerned with getting data to work for us, to give us
its (presumed) hidden treasures. Data science has been called "the
sexiest job of the 21st century". Even if you don't want to become a
professonial data scientist, it's helpful to master the basic concepts
if you want to succeed in today's data-driven business.

This course focuses on data science basics, simple visualization and
productivity tools.

* Target audience

The course is for anyone who is interested in becoming more data
literate in their own field of interest - be it languages, theatre,
biology, psychology or exercise science - and growing their personal
skill stack.

Visualization of data-driven insights and improved productivity when
working with data and media is a concern for any professional.

* Student Learning Outcomes

Students who complete "Introduction to data science" (DSC 105) will be
able to:

- Learn computer and data science principles by playing with data
- Acquire basic statistical programming skills using R
- Apply literate programming principles to their work with Org-mode
- Use infrastructure including command line, Emacs, and GitHub
- Understand the relationship of humans, machines, and data
- Develop their critical thinking skills
- Know how to effectively present assignment and project results

Students, who complete DSC 105 will have fulfilled the prerequisites
for DSC 205, Introduction to advanced data science, which focuses on
coding, data science on the command line, and R packages.

* Course requirements

Formal prerequisites: Introduction to Programming (either CSC100 or
CSC115 or CSC109, and MTH101 (College Algebra).

Otherwise no prior knowledge required. Some knowledge of, and
experience with computers is useful but not critical. Curiosity is
essential. You will gain data literacy skills by taking this
course. The course will prepare you for further studies in computer
and data science, or in other disciplines that use modern computing,
i.e. every discipline, from accounting to zoology).

* Grading

| WHEN       | DESCRIPTION        | IMPACT |
|------------+--------------------+--------|
| TBD        | Final exam         |    25% |
| Last week  | Final presentation |    25% |
| Weekly     | Practice           |    25% |
| Weekly     | Tests              |    25% |

To pass: 50%

* [[https://docs.google.com/document/d/1ZaoAIX7rdBOsRntBxPk7TK77Vld9NXECVLvT9_Jovwc/edit?usp=sharing][Standard Policies (Spring 2023)]]
* [[https://tinyurl.com/LyonPolicy][Assignments and Honor Code and Attendance Policy]]
* Dates and class schedule (TBC)
