#+title: CSC301/CSC401 Internship Seminar Syllabus Spring
#+author: Marcus Birkenkrahe
#+startup: overview hideblocks indent
#+options: toc:nil num:1 ^:nil
#+subtitle: 
* General Course Information

- Meeting Times: *by appointment only*
- Meeting place: Derby Science Building room 210
- Professor: Marcus Birkenkrahe
- Professor's Office: Derby Science Building 210
- Phone: (870) 307-7254 (office) / (501) 422-4725 (private)
- Office hours: by appointment
- Textbook: What Color is Your Parachute? by R Bolles (2021)

* Standard and course policies

- *Standard Lyon College Policies* are incorporated into this syllabus
  and can be found at: [[http://www.lyon.edu/standard-course-policies][lyon.edu/standard-course-policies]].

* Objectives

An internship can be an important "rite of passage", allowing you to
test your skills in a real work environment. It can help you to find
out who you are, what you want (or don't want) to do with your life
and your education, it tests your assertiveness and networking skills,
professional attitude,punctuality, stamina leadership issues, and much
more. This course was designed to support you during your internship
and help you make the most of the experience. Depending on the number
of participants, we will meet weekly for max one hour of discussion,
you will write a weekly short (150 words) blog on GitHub, and briefly
present your internship at the end of the course.

* Target audience

This course serves any student who wants to have a successful career
right out of the academic gates. Some topics may also be of topical
interest to you as a student of psychology, or other disciplines
related to success in the workplace.

* Student Learning Outcomes

Students who complete the internship seminar will be able to:

- Know how to effectively present details of their work place
- Make a good first impression at work
- Have clear goals and a system to implement them
- Have a good grasp of work culture and how to operate within it
- Be assertive in the work place
- Be able to network efficiently, both online and offline
- Know their own skills and how to improve them

* Course requirements

No prior knowledge required. You should either have completed an
internship recently (no more than 3 months ago) or have one lined up
within the next month, or be in an internship right now.

* Grading system

You should be able to see your current grade at any time using the
Canvas gradebook for the course. To pass, you need 60%.

| DESCRIPTION                  | IMPACT |
|------------------------------+--------|
| Weekly blog post assignments |    25% |
| Internship presentations     |    25% |
| Participation                |    50% |

* Learning Management System (LMS)

We will use Canvas and GitHub in this course.

* Schedule and session content

For *important dates*, see the academic Calendar at: catalog.lyon.edu.

Upload your blogs to private repo in GitHub. See table below for order
of blogging.

#+name: tab:schedule
| WEEK | BLOG POST               |
|------+-------------------------|
|    1 | Your hiring process     |
|    2 | Your first impressions  |
|    3 | Your internship goals   |
|    4 | Your internship system  |
|    5 | Your work culture       |
|    6 | Your assertiveness      |
|    7 | Your networking         |
|    8 | Your work values        |
|    9 | Your work hierarchy     |
|   10 | Your skills             |
|   11 | Your accomplishments    |
|   12 | Your career aspirations |
|   13 | [PRESENTATIONS]         |

* References

Bolles/Brooks (2021). What Color Is Your Parachute? Ten Speed
Press. Online: [[https://www.parachutebook.com/][parachutebook.com]]
