#+TITLE:Data And Process Modelling (DSC482.02) Draft Syllabus
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: Data and Process Modeling Draft Syllabus
#+options: toc:nil
* General Course Information

  - Meeting Times: Tuesday & Thursday, 14:30-15:45 hrs
  - Meeting place: Lyon building computer lab room 104
  - Professor: Marcus Birkenkrahe
  - Office: Derby 210
  - Phone: (870) 307-7254
  - Office hours: Mon-Fri after class
  - Textbooks:
    1) /Model Thinking: What You Need To Make Data Work For You/, by
       Scott E. Page, Reprint edition, Basic Books (March 16,
       2021). ([[https://www.amazon.com/Model-Thinker-What-Need-Know/dp/1541675711/][Amazon]])
    2) /Exploring Modeling with Data and Differential Equations Using
       R/, by John M. Zobitz, Version 3.0.0 (Online: [[https://jmzobitz.github.io/ModelingWithR/][jmzobitz.github.io]])

* Objectives

   Models are abstractions that explain parts of the real world,
   e.g. to address, if not solve, complex problems like climate
   change, pandemics, or space exploration. Since the real world is
   only accessible to us through observation, observable data are key
   to building, verifying and using models. To support
   decision-making, data and processes are mined and modeled. In this
   course, we will explore model thinking and a wide array of data and
   process modeling tools. This special topic seminar is for everyone
   who is interested in using models and modeling languages to better
   understand the challenges and achievements of modeling.

* Student Learning Outcomes

   Students who complete DSC 482.02 are able to:

   - Understand data and process modeling challenges
   - Use a variety of modeling languages to create models
   - Make use of different modeling software environments
   - Understand, and can present current modeling research
   - Apply modeling tools to an area of their knowledge
   - Present or write a scientific (IMRaD) essay on modern modeling
     methods

* Course requirements

   Formal prerequisites: MTH 101 (College Algebra), otherwise no prior
   knowledge required. Experience and knowledge of data or process
   modeling methods (e.g. Entity Relationship Diagrams, or Unified
   Modeling Language) is useful but not critical. Curiosity and active
   participations, especially during classroom presentations and
   discussion, is important. You will gain advanced data and process
   literacy skills by taking this course.

* Grading

   | WHEN       | DESCRIPTION        | IMPACT |
   |------------+--------------------+--------|
   | TBD        | Final exam         |    25% |
   | Last week  | Final presentation |    25% |
   | Weekly     | Practice           |    25% |
   | Weekly     | Tests              |    25% |

   To pass: 50%
   
* Dates and class schedule (TBC)
* [[https://docs.google.com/document/d/1ZaoAIX7rdBOsRntBxPk7TK77Vld9NXECVLvT9_Jovwc/edit?usp=sharing][Standard Policies (Spring 2023)]]
* [[https://tinyurl.com/LyonPolicy][Assignments and Honor Code and Attendance Policy]]
