#+TITLE:Data And Process Modelling (DSC482.02) Draft Syllabus
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: Data and Process Modeling Draft Syllabus
#+options: toc:nil
* General Course Information

  - Meeting Times: Tuesday & Thursday, 14:30-15:45 hrs
  - Meeting place: Derby Science Center computer lab 209
  - Professor: Marcus Birkenkrahe
  - Office: Derby Science Center room 210
  - Phone: (870) 307-7254
  - Office hours: MWF 10-10.30am, 2-4.30pm / TTH 9.30-11am, 12.15-2.15pm
  - Some textbooks that we'll be using:
    1) /Model Thinking: What You Need To Make Data Work For You/, by
       Scott E. Page, Basic Books, 2021. URL: [[https://sites.lsa.umich.edu/scottepage/home/the-model-thinker/][umich.edu]].
    2) /Modeling and Simulation in Python/, by Allen B. Downey, NoStarch
       Press, 2023. URL: [[https://greenteapress.com/wp/modsimpy/][greenteapress.com]].
    3) /Exploring Modeling with Data and Differential Equations Using
       R/, by J.M. Zobitz, Version 3.0.0. URL: [[https://jmzobitz.github.io/ModelingWithR/][jmzobitz.github.io]].
    4) /Modeling and Simulation in Python/ by J.M. Kinser. CRC Press,
       2022). URL: [[https://doi.org/10.1201/9781003226581][doi.org/10.1201/9781003226581]].
    5) /Modeling Change and Uncertainty/ by W.P. Fox and R.E. Burks. CRC
       Press, 2022. URL: [[https://doi.org/10.1201/9781003298762][doi.org/10.1201/9781003298762]]
    6) /An introduction to mathematical modeling/ by E.A. Bender,
       Wiley, 1978. Online: [[https://www.google.com/books/edition/An_Introduction_to_Mathematical_Modeling/adf515kSDOkC?hl=en][books.google.com]].

* Objectives

   Models are abstractions that explain parts of the real world,
   e.g. to address, if not solve, complex problems like climate
   change, pandemics, or space exploration. Since the real world is
   only accessible to us through observation, observable data are key
   to building, verifying and using models. To support
   decision-making, data and processes are mined and modeled. In this
   course, we will explore model thinking and a wide array of data and
   process modeling tools. This special topic seminar is for everyone
   who is interested in using models and modeling languages to better
   understand the challenges and achievements of modeling.

   Models can be explored mathematically and/or computationally via
   simulations in a computer. We will explore the use of R and/or
   Python to bring models froma variety of backgrounds to life,
   including: epidemiology, the physics of toilet paper, bungee
   jumping, and even Spider-Man.

   Models can help us deal with the increasing complexity of our
   world, and understanding them will help us deal with many claims
   made by scientists and non-scientists about complex issues. Model
   literacy is an essential 21st century skill.

* Student Learning Outcomes

   Students who complete DSC 482.02 are able to:

   - Understand data and process modeling challenges
   - Use a variety of modeling languages to create models
   - Make use of different modeling software environments
   - Understand, and can present current modeling research
   - Apply modeling tools to an area of their knowledge
   - Present or write a scientific (IMRaD) essay on modern modeling
     methods

* Course requirements

   Formal prerequisites: MTH 101 (College Algebra), otherwise no prior
   knowledge required. Experience and knowledge of data or process
   modeling methods (e.g. Entity Relationship Diagrams, or Unified
   Modeling Language) is useful but not critical. Curiosity and active
   participations, especially during classroom presentations and
   discussion, is important. You will gain advanced data and process
   literacy skills by taking this course.

* Grading

   | WHEN       | DESCRIPTION        | IMPACT |
   |------------+--------------------+--------|
   | TBD        | Final exam         |    25% |
   | Last week  | Final presentation |    25% |
   | Weekly     | Practice           |    25% |
   | Weekly     | Tests              |    25% |

   To pass: 50%
   
* Dates and class schedule (TBC)
* [[https://docs.google.com/document/d/1ZaoAIX7rdBOsRntBxPk7TK77Vld9NXECVLvT9_Jovwc/edit?usp=sharing][Standard Policies (Spring 2023)]]
* [[https://tinyurl.com/LyonPolicy][Assignments and Honor Code and Attendance Policy]]
