#+TITLE:Org
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE: Org for my courses @ Lyon College
#+OPTIONS: toc:nil
* What's here?

  This repo contains `.org` files (Emacs Org-mode) that render
  automatically as markdown. To see a table of contents, open the
  bullet point list on the upper left of the page.

  For the mobile GitHub app, you need the Markdown *.md files.

  To be up to date, you should fork this repo to your own GitHub space
  and fetch upstream when your repo is behind.

* [[https://github.com/birkenkrahe/org/blob/master/spring22.md][Short introduction to my upcoming courses]]

  A short introduction to upcoming courses in Spring term 2022. Please
  ask if anything here is unclear. Full information will be available
  in the syllabi.
  
* [[https://github.com/birkenkrahe/org/blob/master/FAQ.md][Frequently Asked Questions]]

  These are FAQs for all my courses. Each course also carries a local
  FAQ file in the respective repo.

* [[https://github.com/birkenkrahe/org/blob/master/diary.md][Diary]]

  These are irregular notes that I write on topics concerning all
  courses. Each course also has a wiki where I write course-specific
  content.

* [[https://github.com/birkenkrahe/org/discussions][Discussions]]

  Discussion forum on anything in this repo, or anything that's
  relevant across all courses.

* Project management

  I work with [[https://scrum.org][Scrum]] (an agile project management method) in all my
  courses. Relevant materials are also here.
